### ISSUE TITLE
manjaro  build  has  some problems

### ISSUE THREAD

**Issue by runner0353** [huangfeidian/meta#1]
./example/generate_enum
warning: c++: 'linker' input unused [-Wunused-command-line-argument]
/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/move.h:76:27: error: no type named 'remove_reference' in namespace 'std'
/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/move.h:76:43: error: expected ')'
/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/move.h:76:12: note: to match this '('
/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/move.h:77:33: error: use of undeclared identifier '__t'
/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/move.h:87:27: error: no type named 'remo

**Comment by huangfeidian** [comment]
Code compiles fine on my linux machine with gcc 9.2 It seems that your gcc enviroment is corrupt with some macro or some compile flags. Same issue is found at https://github.com/tensorflow/tensorflow/issues/21045. You may look into the issue link for help.
